//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public int Supplier { get; set; }
        public int Customer { get; set; }
        public int Price { get; set; }
        public string Service { get; set; }
        public System.DateTime Date { get; set; }
        public int InvoiceNumber { get; set; }
        public byte IsDeleted { get; set; }
    
        public virtual Person PersonCustomer { get; set; }
        public virtual Person PersonSupplier { get; set; }
    }
}
